# -*- coding: utf-8 -*-

import scrapy
from datetime import datetime


class QuotesSpider(scrapy.Spider):
    name = "gak"

    def start_requests(self):
        urls = [
"https://www.gakkou.net/daigaku/view/index_10436.html", "https://www.gakkou.net/daigaku/view/index_10276.html", "https://www.gakkou.net/daigaku/view/index_10437.html", "https://www.gakkou.net/daigaku/view/index_10300.html", "https://www.gakkou.net/daigaku/view/index_10687.html", "https://www.gakkou.net/daigaku/view/index_10301.html", "https://www.gakkou.net/daigaku/view/index_10127.html", "https://www.gakkou.net/daigaku/view/index_10238.html", "https://www.gakkou.net/daigaku/view/index_10031.html", "https://www.gakkou.net/daigaku/view/index_10237.html", "https://www.gakkou.net/daigaku/view/index_10627.html", "https://www.gakkou.net/daigaku/view/index_10215.html", "https://www.gakkou.net/daigaku/view/index_10583.html", "https://www.gakkou.net/daigaku/view/index_10095.html", "https://www.gakkou.net/daigaku/view/index_10322.html", "https://www.gakkou.net/daigaku/view/index_10732.html", "https://www.gakkou.net/daigaku/view/index_10398.html", "https://www.gakkou.net/daigaku/view/index_10394.html", "https://www.gakkou.net/daigaku/view/index_10547.html", "https://www.gakkou.net/daigaku/view/index_10263.html", "https://www.gakkou.net/daigaku/view/index_10765.html", "https://www.gakkou.net/daigaku/view/index_10363.html", "https://www.gakkou.net/daigaku/view/index_10015.html", "https://www.gakkou.net/daigaku/view/index_10577.html", "https://www.gakkou.net/daigaku/view/index_10315.html", "https://www.gakkou.net/daigaku/view/index_10339.html", "https://www.gakkou.net/daigaku/view/index_10697.html", "https://www.gakkou.net/daigaku/view/index_10058.html", "https://www.gakkou.net/daigaku/view/index_10036.html", "https://www.gakkou.net/daigaku/view/index_10258.html", "https://www.gakkou.net/daigaku/view/index_10004.html", "https://www.gakkou.net/daigaku/view/index_10308.html", "https://www.gakkou.net/daigaku/view/index_10139.html", "https://www.gakkou.net/daigaku/view/index_10486.html", "https://www.gakkou.net/daigaku/view/index_10288.html", "https://www.gakkou.net/daigaku/view/index_10795.html", "https://www.gakkou.net/daigaku/view/index_10667.html", "https://www.gakkou.net/daigaku/view/index_10648.html", "https://www.gakkou.net/daigaku/view/index_10525.html", "https://www.gakkou.net/daigaku/view/index_10805.html", "https://www.gakkou.net/daigaku/view/index_10624.html", "https://www.gakkou.net/daigaku/view/index_10739.html", "https://www.gakkou.net/daigaku/view/index_10446.html", "https://www.gakkou.net/daigaku/view/index_10611.html", "https://www.gakkou.net/daigaku/view/index_10569.html", "https://www.gakkou.net/daigaku/view/index_10606.html", "https://www.gakkou.net/daigaku/view/index_10077.html", "https://www.gakkou.net/daigaku/view/index_10809.html", "https://www.gakkou.net/daigaku/view/index_10005.html", "https://www.gakkou.net/daigaku/view/index_10760.html",
"https://www.gakkou.net/daigaku/view/index_10653.html", "https://www.gakkou.net/daigaku/view/index_10219.html", "https://www.gakkou.net/daigaku/view/index_10774.html", "https://www.gakkou.net/daigaku/view/index_10519.html", "https://www.gakkou.net/daigaku/view/index_10309.html", "https://www.gakkou.net/daigaku/view/index_10216.html", "https://www.gakkou.net/daigaku/view/index_10282.html", "https://www.gakkou.net/daigaku/view/index_10770.html", "https://www.gakkou.net/daigaku/view/index_10003.html", "https://www.gakkou.net/daigaku/view/index_10118.html", "https://www.gakkou.net/daigaku/view/index_10224.html", "https://www.gakkou.net/daigaku/view/index_10209.html", "https://www.gakkou.net/daigaku/view/index_10383.html", "https://www.gakkou.net/daigaku/view/index_10731.html", "https://www.gakkou.net/daigaku/view/index_10400.html", "https://www.gakkou.net/daigaku/view/index_10406.html", "https://www.gakkou.net/daigaku/view/index_10426.html", "https://www.gakkou.net/daigaku/view/index_10443.html", "https://www.gakkou.net/daigaku/view/index_10471.html", "https://www.gakkou.net/daigaku/view/index_10701.html", "https://www.gakkou.net/daigaku/view/index_10053.html", "https://www.gakkou.net/daigaku/view/index_10060.html", "https://www.gakkou.net/daigaku/view/index_10316.html", "https://www.gakkou.net/daigaku/view/index_10658.html", "https://www.gakkou.net/daigaku/view/index_10771.html", "https://www.gakkou.net/daigaku/view/index_10247.html", "https://www.gakkou.net/daigaku/view/index_10722.html", "https://www.gakkou.net/daigaku/view/index_10103.html", "https://www.gakkou.net/daigaku/view/index_10663.html", "https://www.gakkou.net/daigaku/view/index_10191.html", "https://www.gakkou.net/daigaku/view/index_10823.html", "https://www.gakkou.net/daigaku/view/index_10677.html", "https://www.gakkou.net/daigaku/view/index_10065.html", "https://www.gakkou.net/daigaku/view/index_10393.html", "https://www.gakkou.net/daigaku/view/index_10293.html", "https://www.gakkou.net/daigaku/view/index_10239.html", "https://www.gakkou.net/daigaku/view/index_10014.html", "https://www.gakkou.net/daigaku/view/index_10022.html", "https://www.gakkou.net/daigaku/view/index_10101.html", "https://www.gakkou.net/daigaku/view/index_10269.html", "https://www.gakkou.net/daigaku/view/index_10367.html", "https://www.gakkou.net/daigaku/view/index_10392.html", "https://www.gakkou.net/daigaku/view/index_10680.html", "https://www.gakkou.net/daigaku/view/index_10551.html", "https://www.gakkou.net/daigaku/view/index_10555.html", "https://www.gakkou.net/daigaku/view/index_10617.html", "https://www.gakkou.net/daigaku/view/index_10200.html", "https://www.gakkou.net/daigaku/view/index_10693.html", "https://www.gakkou.net/daigaku/view/index_10788.html", "https://www.gakkou.net/daigaku/view/index_10087.html",
"https://www.gakkou.net/daigaku/view/index_10090.html", "https://www.gakkou.net/daigaku/view/index_10092.html", "https://www.gakkou.net/daigaku/view/index_10133.html", "https://www.gakkou.net/daigaku/view/index_10448.html", "https://www.gakkou.net/daigaku/view/index_10572.html", "https://www.gakkou.net/daigaku/view/index_10576.html", "https://www.gakkou.net/daigaku/view/index_10733.html", "https://www.gakkou.net/daigaku/view/index_10335.html", "https://www.gakkou.net/daigaku/view/index_10344.html", "https://www.gakkou.net/daigaku/view/index_10100.html", "https://www.gakkou.net/daigaku/view/index_10384.html", "https://www.gakkou.net/daigaku/view/index_10681.html", "https://www.gakkou.net/daigaku/view/index_10478.html", "https://www.gakkou.net/daigaku/view/index_10346.html", "https://www.gakkou.net/daigaku/view/index_10148.html", "https://www.gakkou.net/daigaku/view/index_10149.html", "https://www.gakkou.net/daigaku/view/index_10249.html", "https://www.gakkou.net/daigaku/view/index_10255.html", "https://www.gakkou.net/daigaku/view/index_10523.html", "https://www.gakkou.net/daigaku/view/index_10496.html", "https://www.gakkou.net/daigaku/view/index_10699.html", "https://www.gakkou.net/daigaku/view/index_10385.html", "https://www.gakkou.net/daigaku/view/index_10459.html", "https://www.gakkou.net/daigaku/view/index_10643.html", "https://www.gakkou.net/daigaku/view/index_10682.html", "https://www.gakkou.net/daigaku/view/index_10041.html", "https://www.gakkou.net/daigaku/view/index_10683.html", "https://www.gakkou.net/daigaku/view/index_10007.html", "https://www.gakkou.net/daigaku/view/index_10487.html", "https://www.gakkou.net/daigaku/view/index_10137.html", "https://www.gakkou.net/daigaku/view/index_10600.html", "https://www.gakkou.net/daigaku/view/index_10140.html", "https://www.gakkou.net/daigaku/view/index_10727.html", "https://www.gakkou.net/daigaku/view/index_10144.html", "https://www.gakkou.net/daigaku/view/index_10513.html", "https://www.gakkou.net/daigaku/view/index_10028.html", "https://www.gakkou.net/daigaku/view/index_10391.html", "https://www.gakkou.net/daigaku/view/index_10186.html", "https://www.gakkou.net/daigaku/view/index_10196.html", "https://www.gakkou.net/daigaku/view/index_10453.html", "https://www.gakkou.net/daigaku/view/index_10454.html", "https://www.gakkou.net/daigaku/view/index_10160.html", "https://www.gakkou.net/daigaku/view/index_10115.html", "https://www.gakkou.net/daigaku/view/index_10365.html", "https://www.gakkou.net/daigaku/view/index_10511.html", "https://www.gakkou.net/daigaku/view/index_10286.html", "https://www.gakkou.net/daigaku/view/index_10052.html", "https://www.gakkou.net/daigaku/view/index_10371.html", "https://www.gakkou.net/daigaku/view/index_10122.html", "https://www.gakkou.net/daigaku/view/index_10222.html",
"https://www.gakkou.net/daigaku/view/index_10462.html", "https://www.gakkou.net/daigaku/view/index_10205.html", "https://www.gakkou.net/daigaku/view/index_10047.html", "https://www.gakkou.net/daigaku/view/index_10575.html"
   ]

        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        for quote in response.css('body'):
            yield{
                "学校名": response.css("th:contains('学校名') + td").xpath('string()').extract_first(),
                "学校区分": response.css("th:contains('学校区分') + td").xpath('string()').extract_first(),
                "設置区分": response.css("th:contains('設置区分') + td").xpath('string()').extract_first(),
                "所在地": response.css("th:contains('所在地') + td").xpath('string()').extract_first(),
                "電話番号": response.css("th:contains('電話番号') + td").xpath('string()').extract_first(),
                "取得時間": datetime.now().strftime("%Y/%m/%d %H:%M:%S"),
            }

    custom_settings = {
        "DOWNLOAD_DELAY": 3.0,
    }
